#!/usr/bin/env ruby

require "fileutils"

directories = Dir.glob('*').select {|f| File.directory? f}
directories.each do |dir|
	full_path = File.join(Dir.pwd, dir)
	next unless Dir.glob(File.join(full_path, ".multirepo")).any?
	
	puts "Migrating multirepo-enabled directory #{dir}"
	
	previous_directory = Dir.pwd
	Dir.chdir(full_path)
	
	puts "Removing unused hooks..."
	FileUtils.rm_f(".git/hooks/prepare-commit-msg")
	FileUtils.rm_f(".git/hooks/post-merge")

	puts "Initializing extras..."
	system('multi init --extras')
	
	Dir.chdir(previous_directory)
end