#!/usr/bin/env ruby

require_relative "core"

version = ARGV[0]

unless version
  puts "Please specify a migration version"
  exit 1
end

migration_filename = "migration-#{version}.rb"
migration_file = File.join(File.dirname(__FILE__), migration_filename)

unless File.exists?(migration_file)
  puts "No migration script exists for version #{version}"
  exit 1
end

puts "Performing migration to version #{version}"

require_relative migration_file

puts "Locating multirepo-enabled repositories..."
multirepo_files = Dir.glob("**/*/.multirepo")
multirepo_repos = multirepo_files.map { |f| File.join(Dir.pwd, File.dirname(f)) }

puts "The following multirepo-enabled repositories will be migrated:"
multirepo_repos.each { |r| puts "--> #{r}" }

exit 1 unless ask_yes_no("Proceed?")

multirepo_repos.each do |repo|
  puts "Migrating #{repo} to git-multirepo version #{version}"
  perform_migration(Migration, repo)
end