#!/usr/bin/env ruby

require "git-multirepo"
require_relative "core"

version = ARGV[0]

unless version
  MultiRepo::Console.log_error("Please specify a migration version")
  exit 1
end

migration_filename = "migration-#{version}.rb"
migration_file = File.join(File.dirname(__FILE__), migration_filename)

unless File.exists?(migration_file)
  puts "No migration script exists for version #{version}"
  exit 1
end

MultiRepo::Console.log_step("Performing migration to version #{version}")

require_relative migration_file

MultiRepo::Console.log_substep("Locating multirepo-enabled repositories...")
multirepo_files = Dir.glob("**/*/.multirepo")
multirepo_repos = multirepo_files.map { |f| File.join(Dir.pwd, File.dirname(f)) }

unless multirepo_repos.any?
  MultiRepo::Console.log_error("No multirepo-enabled repositories were found in #{Dir.pwd}")
  exit 1
end

MultiRepo::Console.log_info("The following multirepo-enabled repositories will be migrated:")
multirepo_repos.each { |r| puts "--> #{r}" }

exit 1 unless MultiRepo::Console.ask("Proceed?")

multirepo_repos.each do |repo|
  MultiRepo::Console.log_substep("Migrating #{repo} to git-multirepo version #{version}")
  perform_migration(Migration, repo)
end